trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "Simulating Maven Build..."
  displayName: 'Build'

- script: echo "Simulating Artifact Publish..."
  displayName: 'Publish Artifact'